name: back_location_android
description: Android implementation of the location plugin
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: back_location
    platforms:
      android:
        package: com.rideamigos.back_location
        pluginClass: LocationPlugin

dependencies:
  flutter:
    sdk: flutter
  back_location_platform_interface:
    git:
      url: https://github.com/RideAmigosCorp/back_location.git
      path: packages/back_location_platform_interface/
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0+1
