name: location
description: This librarie aims at providing you a simple way to get the user location without thinking about permission.
homepage: https://docs.page/Lyokone/flutterlocation
repository: https://github.com/Lyokone/flutterlocation
version: 5.0.0-dev.9
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: location_android
      ios:
        default_package: location_ios

dependencies:
  flutter:
    sdk: flutter
  location_android:
    path: "../location_android"
  location_ios:
    path: "../location_ios"
  location_platform_interface:
    path: "../location_platform_interface"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.0
