name: back_location
description: This librarie aims at providing you a simple way to get the user
  location without thinking about permission.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: back_location_android
      ios:
        default_package: back_location_ios

dependencies:
  back_location_android:
    git:
      url: https://github.com/RideAmigosCorp/back_location.git
      path: packages/back_location_android/
      ref: main
  back_location_ios:
    git:
      url: https://github.com/RideAmigosCorp/back_location.git
      path: packages/back_location_ios/
      ref: main
  back_location_platform_interface:
    git:
      url: https://github.com/RideAmigosCorp/back_location.git
      path: packages/back_location_platform_interface/
      ref: main
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.0
